[package]
name = "wgpu-tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
env_logger = "0.11.8"
log = "0.4.28"
pollster = "0.4.0"
wgpu = "26.0.1"
winit = { version = "0.30.12", features = ["android-native-activity"] }
